### ISSUE TITLE
大佬nb

### ISSUE THREAD

**Issue by Fengqiv** [hzz765/robFoodDD#1]

**Comment by Fengqiv** [comment]
叮咚目前站点只卖，防疫盲盒礼包，还缺货。
不知 美团买菜 可以搞吗？

**Comment by hzz765** [comment]
> 叮咚目前站点只卖，防疫盲盒礼包，还缺货。 不知 美团买菜 可以搞吗？

美团买菜抓包需要早起😂，所以暂时没有相关计划
