### ISSUE TITLE
关于cookies

### ISSUE THREAD

**Issue by hugoshao** [hzz765/robFoodDD#13]
已经连上fiddler了，请问一下是哪个URL下的数据？ 我找了好久没找到，请大佬指教

**Comment by hugoshao** [comment]
另外问一下，登陆后直接访问APP是否可以获取到cookies，还是必须在抓包中登陆？ 连上fiddler之后就无法登陆了，点不了验证码获取按钮

**Comment by hele204** [comment]
你随便找个maicai.api.ddxq.mobi 或者 sunquan.api.ddxq.mobi 都可以

**Comment by hugoshao** [comment]
谢谢回复，我查看了大多数了maicai和sunquan，大多数响应头和请求头都是空的（如下图） ，原数据也是没有其他信息的。
![image](https://user-images.githubusercontent.com/36898061/162174412-81f80376-4f23-479b-81cb-b76398c48175.png)
![image](https://user-images.githubusercontent.com/36898061/162174456-10ab9a2a-ee15-4d0e-ac20-1feecee5e8a6.png)

**Comment by hugoshao** [comment]
新版可用 :)

**Comment by kyh1219** [comment]
我下载最新的fiddler抓包cookie还是都为空，求解

**Comment by 1448399491** [comment]
> 我下载最新的fiddler抓包cookie还是都为空，求解

ios使用thor抓包很方便
