### ISSUE TITLE
上海市闵行区新虹街道这块有下单成功的吗、本站点暂停服务这种情况如何应对

### ISSUE THREAD

**Issue by lslz627** [hzz765/robFoodDD#17]
如题：
新虹街道属于华漕配送站点负责、目前该站点通知，本站点暂停服务，

各位大佬有什么办法绕过去吗

**Comment by zijianziye** [comment]
绕过去也没人送，轻则退款，重则封号吧

**Comment by lslz627** [comment]
> 绕过去也没人送，轻则退款，重则封号吧

好吧、谢谢老哥提醒、老哥是叮咚的明白人啊 🤣
