### ISSUE TITLE
谢谢代码，目前见到的最完善的方案了。

### ISSUE THREAD

**Issue by hogannnn** [hzz765/robFoodDD#2]
有两个问题需要请教一下，需要输入的参数可以提前预设好吗？这样就可以crontab到点自动运行。另外刷新配送时段的等待时间，有没有可能通过生成一个随机数来让刷新时间不固定，降低封号概率？

**Comment by Hito199806** [comment]
该怎么弄啊，大佬们带带

**Comment by hzz765** [comment]
> 有两个问题需要请教一下，需要输入的参数可以提前预设好吗？这样就可以crontab到点自动运行。另外刷新配送时段的等待时间，有没有可能通过生成一个随机数来让刷新时间不固定，降低封号概率？

第一个问题：技术上是可以的，但我暂时不会更新，请理解～因为按我的理解这个需求是想自动抢6点第一波，但这个脚本提交订单后还需手动付款，所以我觉得不在乎早起那么几分钟，另外那时候服务器压载已经很大了，不建议那个时间点使用自动化脚本，开发这个脚本主要是可以白天捡漏，不用人力一直刷新。

第二个问题：可以生成随机数，但不一定能降低封号概率，今天有空的时候会更新一下。

**Comment by hogannnn** [comment]
感谢回复🙏，没有golang基础，昨晚试着改了一下，曲线通过strings再给bufio读取实现了第一点，不过遇上人多提交订单也是失败。那段时间也一直在手点，确实也没差自动运行的几分钟😂

另外可能因为部署在debian上，apt自动安装的golang版本比较低，尝试第二点的时候一直报错，就没有继续做下去。

**Comment by hzz765** [comment]
> 感谢回复🙏，没有golang基础，昨晚试着改了一下，曲线通过strings再给bufio读取实现了第一点，不过遇上人多提交订单也是失败。那段时间也一直在手点，确实也没差自动运行的几分钟😂
> 
> 另外可能因为部署在debian上，apt自动安装的golang版本比较低，尝试第二点的时候一直报错，就没有继续做下去。

随机数已更新，你可以再尝试一下
[https://github.com/hzz765/robFoodDD/commit/10ddf4b778aa70b6f01ca94a69ed535f8faa8edf](url)

**Comment by hogannnn** [comment]
> > 感谢回复🙏，没有golang基础，昨晚试着改了一下，曲线通过strings再给bufio读取实现了第一点，不过遇上人多提交订单也是失败。那段时间也一直在手点，确实也没差自动运行的几分钟😂
> > 另外可能因为部署在debian上，apt自动安装的golang版本比较低，尝试第二点的时候一直报错，就没有继续做下去。
> 
> 随机数已更新，你可以再尝试一下 [https://github.com/hzz765/robFoodDD/commit/10ddf4b778aa70b6f01ca94a69ed535f8faa8edf](url)

测试可以正常使用，用小号一直挂着试试会不会被封，再次感谢！

**Comment by lzb960827** [comment]
@hogannnn 大佬能反馈下用随机数后的封号风险吗 谢谢了

**Comment by hogannnn** [comment]
> @hogannnn 大佬能反馈下用随机数后的封号风险吗 谢谢了

目前没被封，封了会在此issue更新。
