### ISSUE TITLE
大佬，怎么抓cookie呀？

### ISSUE THREAD

**Issue by yeyuchen198** [hzz765/robFoodDD#30]
叮咚买菜没有网页版，难道只能在PC用微信小程序，用Fiddler抓包吗？手机用小黄鸟抓包会被监测到，就不请求了

**Comment by wentiancanye** [comment]
PC微信上用Charles抓。

**Comment by yeyuchen198** [comment]
> 

好的，我待会试试

**Comment by meetcw** [comment]
安卓7以上，APP默认只信任系统证书，抓不了的。用PC试试吧。

**Comment by bug-correcter** [comment]
ios用stream抓包，亲测可以抓到，上海人民加油
