### ISSUE TITLE
大佬抓包 cookie在哪里

### ISSUE THREAD

**Issue by gaoDP123** [hzz765/robFoodDD#32]
![image](https://user-images.githubusercontent.com/34264352/162370479-620e1b63-7bc0-45bb-a768-ec5226622d71.png)

**Comment by HailongJson** [comment]
切到hearder 看请求头

**Comment by gaoDP123** [comment]
> 
![image](https://user-images.githubusercontent.com/34264352/162370735-27596791-91e8-4e55-a0f2-cce566c3f534.png)
我找了  不知道哪个

**Comment by HailongJson** [comment]
实在没有就换个请求看下
![image](https://user-images.githubusercontent.com/30728105/162371246-97b0e6f2-0425-46ef-b0f8-eece162cb11f.png)

**Comment by RtYkk** [comment]
![Fiddler_C41e3qyyss](https://user-images.githubusercontent.com/45971730/162371332-126f1acf-e732-44dd-b548-ba43b3dbb632.png)
我怎么会全都是这种请求……

**Comment by zijianziye** [comment]
> ![image](https://user-images.githubusercontent.com/34264352/162370479-620e1b63-7bc0-45bb-a768-ec5226622d71.png)

抓的包不对

**Comment by HailongJson** [comment]
没装证书不能抓https

**Comment by RtYkk** [comment]
我应该装了啊……神奇。Android 和 Windows 上都装了的

**Comment by HailongJson** [comment]
你可以直接fiddler+pc微信小程序的呀

**Comment by gaoDP123** [comment]
![image](https://user-images.githubusercontent.com/34264352/162375154-4c53bee7-28e1-4362-bce3-8832db4857d7.png)
我这里用pc微信小程序试了下  发现根本没抓到 fiddler也打开从所有程序抓包了

**Comment by gaoDP123** [comment]
我这里尝试了下，没抓到PC 微信小程序的包
![image](https://user-images.githubusercontent.com/34264352/162375369-1ba0428f-c001-48fe-9700-345330bfce62.png)

**Comment by HailongJson** [comment]
你电脑是开了代理吗？你1楼那个包是怎么抓的就还用那种方式吧。多找几个请求再看看，有些请求是不包含cookies的，我这边手机电脑都是可以抓到的。主要看*.ddxq.mobi这些请求就好了

**Comment by Lx34r** [comment]
电脑直接抓请求登录 [这个地址](https://activity.m.ddxq.mobi/#/coupon?code=VERxg&h5_source=caocao&btnType=jumpApp&path=https://u.100.me/m/maicai&random=4)
