### ISSUE TITLE
接口流量被拦截了

### ISSUE THREAD

**Issue by alanleung2017** [hzz765/robFoodDD#4]
########## 生成订单信息【10:29:13】 ###########
{"msg":"系统异常","code":1,"timestamp":"2022-04-07 10:29:13","success":false,"exec_time":null}

**Comment by hzz765** [comment]
> ########## 生成订单信息【10:29:13】 ########### {"msg":"系统异常","code":1,"timestamp":"2022-04-07 10:29:13","success":false,"exec_time":null}

这个错误频繁出现吗？可能是请求过快或服务端那边的原因，你调一下重试间隔再试试看

**Comment by alanleung2017** [comment]
间隔建议怎么调
