### ISSUE TITLE
寄了，老哥，获取时段405报错

### ISSUE THREAD

**Issue by bug-correcter** [hzz765/robFoodDD#49]
@hzz765 老哥快来看看这咋回事儿😂
![image](https://user-images.githubusercontent.com/23416089/162434369-f56f5f6b-597c-4e81-911d-5c88a30d7f41.png)

**Comment by hogannnn** [comment]
#48 参考这个issue

**Comment by bug-correcter** [comment]
更新一波，针对IOS抓包，需要在reserveTime.go里新增一个header参数，key固定是ddmc-uid，这里的value，需要从trackercollect.ddxq.mobi请求的请求主体压缩包中，找到uid的值填入
![image](https://user-images.githubusercontent.com/23416089/162444117-83fc0b7c-4f33-4d1c-be11-98603a39aae7.png)
