### ISSUE TITLE
如何获取cookie

### ISSUE THREAD

**Issue by yzl123456** [hzz765/robFoodDD#6]
请教下如何获取叮咚登录cookie呀？ 要饿死了

**Comment by hanhuoer** [comment]
可以试试 Fiddler，刚抓到了

**Comment by yzl123456** [comment]
大佬，我刚用fidder抓包手机连上电脑的代理之后，手机访问不了叮咚了，有啥高招么？

**Comment by Fengqiv** [comment]
黄鸟

**Comment by hanhuoer** [comment]
> 大佬，我刚用fidder抓包手机连上电脑的代理之后，手机访问不了叮咚了，有啥高招么？

没有网络可能是 ip 代理没配置正确，可以网上找一找看看他们的经验。

关键字：Fiddler HTTPS 证书 抓包 等等

**Comment by yzl123456** [comment]
现在是能上百度的网，但是上不了叮咚app的

**Comment by yzl123456** [comment]
那边有检测反抓包？

**Comment by yzl123456** [comment]
问一下你们装的fidder版本是多少的呀？

**Comment by hanhuoer** [comment]
> 问一下你们装的fidder版本是多少的呀？

Progress Telerik Fiddler Classic

v5.0.20211.51073 for .NET 4.6.1

64-bit AMD64, VM: 131.0mb, WS: 150.0mb
.NET 4.8 WinNT 10.0.19043.0

---

IOS 15.2
