### ISSUE TITLE
从小程序抓取的cookie 一直报错未查询到有效收货地址，请前往app添加或检查cookie是否正确！

### ISSUE THREAD

**Issue by Howee-Liu** [hzz765/robFoodDD#8]
从小程序抓取的cookie 一直报错未查询到有效收货地址，请前往app添加或检查cookie是否正确！
可否协助查看一下·？
或者这个怎么可以排错
新手go 不是很懂

**Comment by Howee-Liu** [comment]
![image](https://user-images.githubusercontent.com/103171809/162137178-358f2f3c-244c-4751-bd2e-790eb6d695aa.png)

**Comment by hzz765** [comment]
> 从小程序抓取的cookie 一直报错未查询到有效收货地址，请前往app添加或检查cookie是否正确！ 可否协助查看一下·？ 或者这个怎么可以排错 新手go 不是很懂

#7 
重新拉一下代码，之前有个bug

**Comment by Fengqiv** [comment]
![截图_1649315178712](https://user-images.githubusercontent.com/96766709/162140829-aef41c11-b777-4b70-bf70-9751c7e4c93d.png)
请问，这个何解？ @ @hzz765

**Comment by hzz765** [comment]
> ![截图_1649315178712](https://user-images.githubusercontent.com/96766709/162140829-aef41c11-b777-4b70-bf70-9751c7e4c93d.png)
> 
> 请问，这个何解？ @ @hzz765 

重新提个issue吧，我有时间了看看
