### ISSUE TITLE
提交订单时卡在了“您选择的送达时间已经失效了，请重新选择”

### ISSUE THREAD

**Issue by zukunft-001** [hzz765/robFoodDD#9]
提交订单一直提示 **“您选择的送达时间已经失效了，请重新选择”**。

而后面在程序试了几次之后，我马上手动在app上提交订单，在发现配送时间可以选择后就立刻提交了订单成功了，这里是否有些问题导致程序卡住。

<img width="528" alt="WX20220407-150851@2x" src="https://user-images.githubusercontent.com/28802158/162142121-f0def5a8-a572-455b-99e7-c4023020d175.png">

**Comment by hzz765** [comment]
> 提交订单一直提示 **“您选择的送达时间已经失效了，请重新选择”**。
> 
> 而后面在程序试了几次之后，我马上手动在app上提交订单，在发现配送时间可以选择后就立刻提交了订单成功了，这里是否有些问题导致程序卡住。
> 
> <img alt="WX20220407-150851@2x" width="528" src="https://user-images.githubusercontent.com/28802158/162142121-f0def5a8-a572-455b-99e7-c4023020d175.png">

修复代码已提交，第一次写Go，有些不熟练🤦‍，建议使用一个外地可选配送时间的地址先测试一下，若仍不能正常下单再反馈一下

**Comment by zukunft-001** [comment]
> > 提交订单一直提示 **“您选择的送达时间已经失效了，请重新选择”**。
> > 而后面在程序试了几次之后，我马上手动在app上提交订单，在发现配送时间可以选择后就立刻提交了订单成功了，这里是否有些问题导致程序卡住。
> > <img alt="WX20220407-150851@2x" width="528" src="https://user-images.githubusercontent.com/28802158/162142121-f0def5a8-a572-455b-99e7-c4023020d175.png">
> 
> 修复代码已提交，第一次写Go，有些不熟练🤦‍，建议使用一个外地可选配送时间的地址先测试一下，若仍不能正常下单再反馈一下

多谢多谢，辛苦啦。
